//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Chat.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ChatParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, Select=4, InWin=5, Not=6, And=7, Or=8, HasWordOfDict=9, 
		HasTime=10, HasLocation=11, HasOrganization=12, HasURL=13, HasDate=14, 
		HasQuestion=15, HasUserMentioned=16, ByUser=17, STRING=18, INTEGER=19, 
		WS=20;
	public const int
		RULE_query = 0, RULE_body = 1, RULE_restriction_group = 2, RULE_restrictions = 3, 
		RULE_restriction = 4, RULE_condition = 5, RULE_hdict = 6, RULE_huser = 7, 
		RULE_number = 8;
	public static readonly string[] ruleNames = {
		"query", "body", "restriction_group", "restrictions", "restriction", "condition", 
		"hdict", "huser", "number"
	};

	private static readonly string[] _LiteralNames = {
		null, "','", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "Select", "InWin", "Not", "And", "Or", "HasWordOfDict", 
		"HasTime", "HasLocation", "HasOrganization", "HasURL", "HasDate", "HasQuestion", 
		"HasUserMentioned", "ByUser", "STRING", "INTEGER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Chat.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ChatParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ChatParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ChatParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class QueryContext : ParserRuleContext {
		public ITerminalNode Select() { return GetToken(ChatParser.Select, 0); }
		public BodyContext body() {
			return GetRuleContext<BodyContext>(0);
		}
		public QueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QueryContext query() {
		QueryContext _localctx = new QueryContext(Context, State);
		EnterRule(_localctx, 0, RULE_query);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 18; Match(Select);
			State = 19; body();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BodyContext : ParserRuleContext {
		public Restriction_groupContext[] restriction_group() {
			return GetRuleContexts<Restriction_groupContext>();
		}
		public Restriction_groupContext restriction_group(int i) {
			return GetRuleContext<Restriction_groupContext>(i);
		}
		public BodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_body; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BodyContext body() {
		BodyContext _localctx = new BodyContext(Context, State);
		EnterRule(_localctx, 2, RULE_body);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 21; restriction_group();
			State = 26;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 22; Match(T__0);
				State = 23; restriction_group();
				}
				}
				State = 28;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Restriction_groupContext : ParserRuleContext {
		public RestrictionsContext restrictions() {
			return GetRuleContext<RestrictionsContext>(0);
		}
		public ITerminalNode InWin() { return GetToken(ChatParser.InWin, 0); }
		public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public Restriction_groupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restriction_group; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestriction_group(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Restriction_groupContext restriction_group() {
		Restriction_groupContext _localctx = new Restriction_groupContext(Context, State);
		EnterRule(_localctx, 4, RULE_restriction_group);
		try {
			State = 34;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 29; restrictions();
				State = 30; Match(InWin);
				State = 31; number();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 33; restrictions();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RestrictionsContext : ParserRuleContext {
		public RestrictionContext[] restriction() {
			return GetRuleContexts<RestrictionContext>();
		}
		public RestrictionContext restriction(int i) {
			return GetRuleContext<RestrictionContext>(i);
		}
		public RestrictionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restrictions; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestrictions(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RestrictionsContext restrictions() {
		RestrictionsContext _localctx = new RestrictionsContext(Context, State);
		EnterRule(_localctx, 6, RULE_restrictions);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 36; restriction(0);
			State = 41;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 37; Match(T__0);
					State = 38; restriction(0);
					}
					} 
				}
				State = 43;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RestrictionContext : ParserRuleContext {
		public RestrictionContext[] restriction() {
			return GetRuleContexts<RestrictionContext>();
		}
		public RestrictionContext restriction(int i) {
			return GetRuleContext<RestrictionContext>(i);
		}
		public ITerminalNode Not() { return GetToken(ChatParser.Not, 0); }
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public ITerminalNode And() { return GetToken(ChatParser.And, 0); }
		public ITerminalNode Or() { return GetToken(ChatParser.Or, 0); }
		public RestrictionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restriction; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestriction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RestrictionContext restriction() {
		return restriction(0);
	}

	private RestrictionContext restriction(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		RestrictionContext _localctx = new RestrictionContext(Context, _parentState);
		RestrictionContext _prevctx = _localctx;
		int _startState = 8;
		EnterRecursionRule(_localctx, 8, RULE_restriction, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 52;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
				{
				State = 45; Match(T__1);
				State = 46; restriction(0);
				State = 47; Match(T__2);
				}
				break;
			case Not:
				{
				State = 49; Match(Not);
				State = 50; restriction(2);
				}
				break;
			case HasWordOfDict:
			case HasTime:
			case HasLocation:
			case HasOrganization:
			case HasURL:
			case HasDate:
			case HasQuestion:
			case HasUserMentioned:
			case ByUser:
				{
				State = 51; condition();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 62;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 60;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
					case 1:
						{
						_localctx = new RestrictionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_restriction);
						State = 54;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 55; Match(And);
						State = 56; restriction(6);
						}
						break;
					case 2:
						{
						_localctx = new RestrictionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_restriction);
						State = 57;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 58; Match(Or);
						State = 59; restriction(5);
						}
						break;
					}
					} 
				}
				State = 64;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		public ITerminalNode HasWordOfDict() { return GetToken(ChatParser.HasWordOfDict, 0); }
		public HdictContext hdict() {
			return GetRuleContext<HdictContext>(0);
		}
		public ITerminalNode HasTime() { return GetToken(ChatParser.HasTime, 0); }
		public ITerminalNode HasLocation() { return GetToken(ChatParser.HasLocation, 0); }
		public ITerminalNode HasOrganization() { return GetToken(ChatParser.HasOrganization, 0); }
		public ITerminalNode HasURL() { return GetToken(ChatParser.HasURL, 0); }
		public ITerminalNode HasDate() { return GetToken(ChatParser.HasDate, 0); }
		public ITerminalNode HasQuestion() { return GetToken(ChatParser.HasQuestion, 0); }
		public ITerminalNode HasUserMentioned() { return GetToken(ChatParser.HasUserMentioned, 0); }
		public HuserContext huser() {
			return GetRuleContext<HuserContext>(0);
		}
		public ITerminalNode ByUser() { return GetToken(ChatParser.ByUser, 0); }
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 10, RULE_condition);
		try {
			State = 98;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case HasWordOfDict:
				EnterOuterAlt(_localctx, 1);
				{
				State = 65; Match(HasWordOfDict);
				State = 66; Match(T__1);
				State = 67; hdict();
				State = 68; Match(T__2);
				}
				break;
			case HasTime:
				EnterOuterAlt(_localctx, 2);
				{
				State = 70; Match(HasTime);
				State = 71; Match(T__1);
				State = 72; Match(T__2);
				}
				break;
			case HasLocation:
				EnterOuterAlt(_localctx, 3);
				{
				State = 73; Match(HasLocation);
				State = 74; Match(T__1);
				State = 75; Match(T__2);
				}
				break;
			case HasOrganization:
				EnterOuterAlt(_localctx, 4);
				{
				State = 76; Match(HasOrganization);
				State = 77; Match(T__1);
				State = 78; Match(T__2);
				}
				break;
			case HasURL:
				EnterOuterAlt(_localctx, 5);
				{
				State = 79; Match(HasURL);
				State = 80; Match(T__1);
				State = 81; Match(T__2);
				}
				break;
			case HasDate:
				EnterOuterAlt(_localctx, 6);
				{
				State = 82; Match(HasDate);
				State = 83; Match(T__1);
				State = 84; Match(T__2);
				}
				break;
			case HasQuestion:
				EnterOuterAlt(_localctx, 7);
				{
				State = 85; Match(HasQuestion);
				State = 86; Match(T__1);
				State = 87; Match(T__2);
				}
				break;
			case HasUserMentioned:
				EnterOuterAlt(_localctx, 8);
				{
				State = 88; Match(HasUserMentioned);
				State = 89; Match(T__1);
				State = 90; huser();
				State = 91; Match(T__2);
				}
				break;
			case ByUser:
				EnterOuterAlt(_localctx, 9);
				{
				State = 93; Match(ByUser);
				State = 94; Match(T__1);
				State = 95; huser();
				State = 96; Match(T__2);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HdictContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(ChatParser.STRING, 0); }
		public HdictContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hdict; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHdict(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HdictContext hdict() {
		HdictContext _localctx = new HdictContext(Context, State);
		EnterRule(_localctx, 12, RULE_hdict);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HuserContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(ChatParser.STRING, 0); }
		public HuserContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_huser; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHuser(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HuserContext huser() {
		HuserContext _localctx = new HuserContext(Context, State);
		EnterRule(_localctx, 14, RULE_huser);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public ITerminalNode INTEGER() { return GetToken(ChatParser.INTEGER, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 16, RULE_number);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104; Match(INTEGER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 4: return restriction_sempred((RestrictionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool restriction_sempred(RestrictionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		case 1: return Precpred(Context, 4);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x16', 'm', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 
		'\x1B', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x1E', '\v', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', 
		'\x4', '%', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', 
		'\x5', '*', '\n', '\x5', '\f', '\x5', '\xE', '\x5', '-', '\v', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\x37', '\n', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\a', '\x6', '?', '\n', '\x6', '\f', '\x6', '\xE', 
		'\x6', '\x42', '\v', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x5', '\a', '\x65', '\n', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x2', '\x3', '\n', '\v', '\x2', '\x4', '\x6', '\b', '\n', '\f', 
		'\xE', '\x10', '\x12', '\x2', '\x2', '\x2', 'r', '\x2', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '\x4', '\x17', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'$', '\x3', '\x2', '\x2', '\x2', '\b', '&', '\x3', '\x2', '\x2', '\x2', 
		'\n', '\x36', '\x3', '\x2', '\x2', '\x2', '\f', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '\xE', '\x66', '\x3', '\x2', '\x2', '\x2', '\x10', 'h', 
		'\x3', '\x2', '\x2', '\x2', '\x12', 'j', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'\x15', '\a', '\x6', '\x2', '\x2', '\x15', '\x16', '\x5', '\x4', '\x3', 
		'\x2', '\x16', '\x3', '\x3', '\x2', '\x2', '\x2', '\x17', '\x1C', '\x5', 
		'\x6', '\x4', '\x2', '\x18', '\x19', '\a', '\x3', '\x2', '\x2', '\x19', 
		'\x1B', '\x5', '\x6', '\x4', '\x2', '\x1A', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', ' ', '\x5', '\b', '\x5', '\x2', ' ', '!', '\a', '\a', '\x2', 
		'\x2', '!', '\"', '\x5', '\x12', '\n', '\x2', '\"', '%', '\x3', '\x2', 
		'\x2', '\x2', '#', '%', '\x5', '\b', '\x5', '\x2', '$', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '$', '#', '\x3', '\x2', '\x2', '\x2', '%', '\a', 
		'\x3', '\x2', '\x2', '\x2', '&', '+', '\x5', '\n', '\x6', '\x2', '\'', 
		'(', '\a', '\x3', '\x2', '\x2', '(', '*', '\x5', '\n', '\x6', '\x2', ')', 
		'\'', '\x3', '\x2', '\x2', '\x2', '*', '-', '\x3', '\x2', '\x2', '\x2', 
		'+', ')', '\x3', '\x2', '\x2', '\x2', '+', ',', '\x3', '\x2', '\x2', '\x2', 
		',', '\t', '\x3', '\x2', '\x2', '\x2', '-', '+', '\x3', '\x2', '\x2', 
		'\x2', '.', '/', '\b', '\x6', '\x1', '\x2', '/', '\x30', '\a', '\x4', 
		'\x2', '\x2', '\x30', '\x31', '\x5', '\n', '\x6', '\x2', '\x31', '\x32', 
		'\a', '\x5', '\x2', '\x2', '\x32', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x34', '\a', '\b', '\x2', '\x2', '\x34', '\x37', '\x5', '\n', 
		'\x6', '\x4', '\x35', '\x37', '\x5', '\f', '\a', '\x2', '\x36', '.', '\x3', 
		'\x2', '\x2', '\x2', '\x36', '\x33', '\x3', '\x2', '\x2', '\x2', '\x36', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x37', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\x39', '\f', '\a', '\x2', '\x2', '\x39', ':', '\a', '\t', 
		'\x2', '\x2', ':', '?', '\x5', '\n', '\x6', '\b', ';', '<', '\f', '\x6', 
		'\x2', '\x2', '<', '=', '\a', '\n', '\x2', '\x2', '=', '?', '\x5', '\n', 
		'\x6', '\a', '>', '\x38', '\x3', '\x2', '\x2', '\x2', '>', ';', '\x3', 
		'\x2', '\x2', '\x2', '?', '\x42', '\x3', '\x2', '\x2', '\x2', '@', '>', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\v', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\a', '\v', '\x2', '\x2', '\x44', '\x45', '\a', '\x4', 
		'\x2', '\x2', '\x45', '\x46', '\x5', '\xE', '\b', '\x2', '\x46', 'G', 
		'\a', '\x5', '\x2', '\x2', 'G', '\x65', '\x3', '\x2', '\x2', '\x2', 'H', 
		'I', '\a', '\f', '\x2', '\x2', 'I', 'J', '\a', '\x4', '\x2', '\x2', 'J', 
		'\x65', '\a', '\x5', '\x2', '\x2', 'K', 'L', '\a', '\r', '\x2', '\x2', 
		'L', 'M', '\a', '\x4', '\x2', '\x2', 'M', '\x65', '\a', '\x5', '\x2', 
		'\x2', 'N', 'O', '\a', '\xE', '\x2', '\x2', 'O', 'P', '\a', '\x4', '\x2', 
		'\x2', 'P', '\x65', '\a', '\x5', '\x2', '\x2', 'Q', 'R', '\a', '\xF', 
		'\x2', '\x2', 'R', 'S', '\a', '\x4', '\x2', '\x2', 'S', '\x65', '\a', 
		'\x5', '\x2', '\x2', 'T', 'U', '\a', '\x10', '\x2', '\x2', 'U', 'V', '\a', 
		'\x4', '\x2', '\x2', 'V', '\x65', '\a', '\x5', '\x2', '\x2', 'W', 'X', 
		'\a', '\x11', '\x2', '\x2', 'X', 'Y', '\a', '\x4', '\x2', '\x2', 'Y', 
		'\x65', '\a', '\x5', '\x2', '\x2', 'Z', '[', '\a', '\x12', '\x2', '\x2', 
		'[', '\\', '\a', '\x4', '\x2', '\x2', '\\', ']', '\x5', '\x10', '\t', 
		'\x2', ']', '^', '\a', '\x5', '\x2', '\x2', '^', '\x65', '\x3', '\x2', 
		'\x2', '\x2', '_', '`', '\a', '\x13', '\x2', '\x2', '`', '\x61', '\a', 
		'\x4', '\x2', '\x2', '\x61', '\x62', '\x5', '\x10', '\t', '\x2', '\x62', 
		'\x63', '\a', '\x5', '\x2', '\x2', '\x63', '\x65', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x43', '\x3', '\x2', '\x2', '\x2', '\x64', 'H', '\x3', 
		'\x2', '\x2', '\x2', '\x64', 'K', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'N', '\x3', '\x2', '\x2', '\x2', '\x64', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'\x64', 'T', '\x3', '\x2', '\x2', '\x2', '\x64', 'W', '\x3', '\x2', '\x2', 
		'\x2', '\x64', 'Z', '\x3', '\x2', '\x2', '\x2', '\x64', '_', '\x3', '\x2', 
		'\x2', '\x2', '\x65', '\r', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', 
		'\x14', '\x2', '\x2', 'g', '\xF', '\x3', '\x2', '\x2', '\x2', 'h', 'i', 
		'\a', '\x14', '\x2', '\x2', 'i', '\x11', '\x3', '\x2', '\x2', '\x2', 'j', 
		'k', '\a', '\x15', '\x2', '\x2', 'k', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\x1C', '$', '+', '\x36', '>', '@', '\x64',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
