//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Chat.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ChatParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, Select=4, InWin=5, Not=6, And=7, Or=8, HasWordOfDict=9, 
		HasTime=10, HasLocation=11, HasOrganization=12, HasUserMentioned=13, ByUser=14, 
		STRING=15, INTEGER=16, WS=17;
	public const int
		RULE_query = 0, RULE_body = 1, RULE_restriction_expr = 2, RULE_restriction = 3, 
		RULE_condition = 4, RULE_hdict = 5, RULE_huser = 6, RULE_number = 7;
	public static readonly string[] ruleNames = {
		"query", "body", "restriction_expr", "restriction", "condition", "hdict", 
		"huser", "number"
	};

	private static readonly string[] _LiteralNames = {
		null, "','", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "Select", "InWin", "Not", "And", "Or", "HasWordOfDict", 
		"HasTime", "HasLocation", "HasOrganization", "HasUserMentioned", "ByUser", 
		"STRING", "INTEGER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Chat.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ChatParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ChatParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ChatParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class QueryContext : ParserRuleContext {
		public ITerminalNode Select() { return GetToken(ChatParser.Select, 0); }
		public BodyContext body() {
			return GetRuleContext<BodyContext>(0);
		}
		public QueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QueryContext query() {
		QueryContext _localctx = new QueryContext(Context, State);
		EnterRule(_localctx, 0, RULE_query);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 16; Match(Select);
			State = 17; body();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BodyContext : ParserRuleContext {
		public Restriction_exprContext[] restriction_expr() {
			return GetRuleContexts<Restriction_exprContext>();
		}
		public Restriction_exprContext restriction_expr(int i) {
			return GetRuleContext<Restriction_exprContext>(i);
		}
		public BodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_body; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BodyContext body() {
		BodyContext _localctx = new BodyContext(Context, State);
		EnterRule(_localctx, 2, RULE_body);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 19; restriction_expr();
			State = 24;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 20; Match(T__0);
				State = 21; restriction_expr();
				}
				}
				State = 26;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Restriction_exprContext : ParserRuleContext {
		public RestrictionContext restriction() {
			return GetRuleContext<RestrictionContext>(0);
		}
		public ITerminalNode InWin() { return GetToken(ChatParser.InWin, 0); }
		public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public Restriction_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restriction_expr; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestriction_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Restriction_exprContext restriction_expr() {
		Restriction_exprContext _localctx = new Restriction_exprContext(Context, State);
		EnterRule(_localctx, 4, RULE_restriction_expr);
		try {
			State = 32;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 27; restriction(0);
				State = 28; Match(InWin);
				State = 29; number();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 31; restriction(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RestrictionContext : ParserRuleContext {
		public RestrictionContext[] restriction() {
			return GetRuleContexts<RestrictionContext>();
		}
		public RestrictionContext restriction(int i) {
			return GetRuleContext<RestrictionContext>(i);
		}
		public ITerminalNode Not() { return GetToken(ChatParser.Not, 0); }
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public ITerminalNode And() { return GetToken(ChatParser.And, 0); }
		public ITerminalNode Or() { return GetToken(ChatParser.Or, 0); }
		public RestrictionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restriction; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestriction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RestrictionContext restriction() {
		return restriction(0);
	}

	private RestrictionContext restriction(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		RestrictionContext _localctx = new RestrictionContext(Context, _parentState);
		RestrictionContext _prevctx = _localctx;
		int _startState = 6;
		EnterRecursionRule(_localctx, 6, RULE_restriction, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 42;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
				{
				State = 35; Match(T__1);
				State = 36; restriction(0);
				State = 37; Match(T__2);
				}
				break;
			case Not:
				{
				State = 39; Match(Not);
				State = 40; restriction(2);
				}
				break;
			case HasWordOfDict:
			case HasTime:
			case HasLocation:
			case HasOrganization:
			case HasUserMentioned:
			case ByUser:
				{
				State = 41; condition();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 52;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 50;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
					case 1:
						{
						_localctx = new RestrictionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_restriction);
						State = 44;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 45; Match(And);
						State = 46; restriction(6);
						}
						break;
					case 2:
						{
						_localctx = new RestrictionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_restriction);
						State = 47;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 48; Match(Or);
						State = 49; restriction(5);
						}
						break;
					}
					} 
				}
				State = 54;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		public ITerminalNode HasWordOfDict() { return GetToken(ChatParser.HasWordOfDict, 0); }
		public HdictContext hdict() {
			return GetRuleContext<HdictContext>(0);
		}
		public ITerminalNode HasTime() { return GetToken(ChatParser.HasTime, 0); }
		public ITerminalNode HasLocation() { return GetToken(ChatParser.HasLocation, 0); }
		public ITerminalNode HasOrganization() { return GetToken(ChatParser.HasOrganization, 0); }
		public ITerminalNode HasUserMentioned() { return GetToken(ChatParser.HasUserMentioned, 0); }
		public HuserContext huser() {
			return GetRuleContext<HuserContext>(0);
		}
		public ITerminalNode ByUser() { return GetToken(ChatParser.ByUser, 0); }
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 8, RULE_condition);
		try {
			State = 79;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case HasWordOfDict:
				EnterOuterAlt(_localctx, 1);
				{
				State = 55; Match(HasWordOfDict);
				State = 56; Match(T__1);
				State = 57; hdict();
				State = 58; Match(T__2);
				}
				break;
			case HasTime:
				EnterOuterAlt(_localctx, 2);
				{
				State = 60; Match(HasTime);
				State = 61; Match(T__1);
				State = 62; Match(T__2);
				}
				break;
			case HasLocation:
				EnterOuterAlt(_localctx, 3);
				{
				State = 63; Match(HasLocation);
				State = 64; Match(T__1);
				State = 65; Match(T__2);
				}
				break;
			case HasOrganization:
				EnterOuterAlt(_localctx, 4);
				{
				State = 66; Match(HasOrganization);
				State = 67; Match(T__1);
				State = 68; Match(T__2);
				}
				break;
			case HasUserMentioned:
				EnterOuterAlt(_localctx, 5);
				{
				State = 69; Match(HasUserMentioned);
				State = 70; Match(T__1);
				State = 71; huser();
				State = 72; Match(T__2);
				}
				break;
			case ByUser:
				EnterOuterAlt(_localctx, 6);
				{
				State = 74; Match(ByUser);
				State = 75; Match(T__1);
				State = 76; huser();
				State = 77; Match(T__2);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HdictContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(ChatParser.STRING, 0); }
		public HdictContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hdict; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHdict(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HdictContext hdict() {
		HdictContext _localctx = new HdictContext(Context, State);
		EnterRule(_localctx, 10, RULE_hdict);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HuserContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(ChatParser.STRING, 0); }
		public HuserContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_huser; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHuser(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HuserContext huser() {
		HuserContext _localctx = new HuserContext(Context, State);
		EnterRule(_localctx, 12, RULE_huser);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public ITerminalNode INTEGER() { return GetToken(ChatParser.INTEGER, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 14, RULE_number);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85; Match(INTEGER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 3: return restriction_sempred((RestrictionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool restriction_sempred(RestrictionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		case 1: return Precpred(Context, 4);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x13', 'Z', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x19', '\n', '\x3', '\f', 
		'\x3', '\xE', '\x3', '\x1C', '\v', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '#', '\n', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '-', '\n', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\a', '\x5', '\x35', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 
		'\x38', '\v', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', 'R', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x2', '\x3', 
		'\b', '\n', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x2', 
		'\x2', '\x2', '\\', '\x2', '\x12', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x6', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\b', ',', '\x3', '\x2', '\x2', '\x2', '\n', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\f', 'S', '\x3', '\x2', '\x2', '\x2', '\xE', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\x10', 'W', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'\x13', '\a', '\x6', '\x2', '\x2', '\x13', '\x14', '\x5', '\x4', '\x3', 
		'\x2', '\x14', '\x3', '\x3', '\x2', '\x2', '\x2', '\x15', '\x1A', '\x5', 
		'\x6', '\x4', '\x2', '\x16', '\x17', '\a', '\x3', '\x2', '\x2', '\x17', 
		'\x19', '\x5', '\x6', '\x4', '\x2', '\x18', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x1E', '\x5', '\b', '\x5', '\x2', '\x1E', '\x1F', '\a', 
		'\a', '\x2', '\x2', '\x1F', ' ', '\x5', '\x10', '\t', '\x2', ' ', '#', 
		'\x3', '\x2', '\x2', '\x2', '!', '#', '\x5', '\b', '\x5', '\x2', '\"', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\"', '!', '\x3', '\x2', '\x2', '\x2', 
		'#', '\a', '\x3', '\x2', '\x2', '\x2', '$', '%', '\b', '\x5', '\x1', '\x2', 
		'%', '&', '\a', '\x4', '\x2', '\x2', '&', '\'', '\x5', '\b', '\x5', '\x2', 
		'\'', '(', '\a', '\x5', '\x2', '\x2', '(', '-', '\x3', '\x2', '\x2', '\x2', 
		')', '*', '\a', '\b', '\x2', '\x2', '*', '-', '\x5', '\b', '\x5', '\x4', 
		'+', '-', '\x5', '\n', '\x6', '\x2', ',', '$', '\x3', '\x2', '\x2', '\x2', 
		',', ')', '\x3', '\x2', '\x2', '\x2', ',', '+', '\x3', '\x2', '\x2', '\x2', 
		'-', '\x36', '\x3', '\x2', '\x2', '\x2', '.', '/', '\f', '\a', '\x2', 
		'\x2', '/', '\x30', '\a', '\t', '\x2', '\x2', '\x30', '\x35', '\x5', '\b', 
		'\x5', '\b', '\x31', '\x32', '\f', '\x6', '\x2', '\x2', '\x32', '\x33', 
		'\a', '\n', '\x2', '\x2', '\x33', '\x35', '\x5', '\b', '\x5', '\a', '\x34', 
		'.', '\x3', '\x2', '\x2', '\x2', '\x34', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x38', '\x3', '\x2', '\x2', '\x2', '\x36', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x36', '\x37', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x38', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ':', '\a', '\v', '\x2', '\x2', ':', ';', '\a', '\x4', '\x2', 
		'\x2', ';', '<', '\x5', '\f', '\a', '\x2', '<', '=', '\a', '\x5', '\x2', 
		'\x2', '=', 'R', '\x3', '\x2', '\x2', '\x2', '>', '?', '\a', '\f', '\x2', 
		'\x2', '?', '@', '\a', '\x4', '\x2', '\x2', '@', 'R', '\a', '\x5', '\x2', 
		'\x2', '\x41', '\x42', '\a', '\r', '\x2', '\x2', '\x42', '\x43', '\a', 
		'\x4', '\x2', '\x2', '\x43', 'R', '\a', '\x5', '\x2', '\x2', '\x44', '\x45', 
		'\a', '\xE', '\x2', '\x2', '\x45', '\x46', '\a', '\x4', '\x2', '\x2', 
		'\x46', 'R', '\a', '\x5', '\x2', '\x2', 'G', 'H', '\a', '\xF', '\x2', 
		'\x2', 'H', 'I', '\a', '\x4', '\x2', '\x2', 'I', 'J', '\x5', '\xE', '\b', 
		'\x2', 'J', 'K', '\a', '\x5', '\x2', '\x2', 'K', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'M', '\a', '\x10', '\x2', '\x2', 'M', 'N', '\a', '\x4', '\x2', 
		'\x2', 'N', 'O', '\x5', '\xE', '\b', '\x2', 'O', 'P', '\a', '\x5', '\x2', 
		'\x2', 'P', 'R', '\x3', '\x2', '\x2', '\x2', 'Q', '\x39', '\x3', '\x2', 
		'\x2', '\x2', 'Q', '>', '\x3', '\x2', '\x2', '\x2', 'Q', '\x41', '\x3', 
		'\x2', '\x2', '\x2', 'Q', '\x44', '\x3', '\x2', '\x2', '\x2', 'Q', 'G', 
		'\x3', '\x2', '\x2', '\x2', 'Q', 'L', '\x3', '\x2', '\x2', '\x2', 'R', 
		'\v', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '\x11', '\x2', '\x2', 
		'T', '\r', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '\x11', '\x2', 
		'\x2', 'V', '\xF', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', '\x12', 
		'\x2', '\x2', 'X', '\x11', '\x3', '\x2', '\x2', '\x2', '\b', '\x1A', '\"', 
		',', '\x34', '\x36', 'Q',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
