//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Chat.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ChatParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, Select=5, InWin=6, Not=7, And=8, Or=9, 
		HasWordOfDict=10, HasTime=11, HasLocation=12, HasOrganization=13, HasURL=14, 
		HasDate=15, HasQuestion=16, HasUserMentioned=17, ByUser=18, STRING=19, 
		INTEGER=20, WS=21;
	public const int
		RULE_query = 0, RULE_body = 1, RULE_restriction_group = 2, RULE_restrictions = 3, 
		RULE_restriction = 4, RULE_condition = 5, RULE_number = 6, RULE_hdict = 7, 
		RULE_huser = 8;
	public static readonly string[] ruleNames = {
		"query", "body", "restriction_group", "restrictions", "restriction", "condition", 
		"number", "hdict", "huser"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "','", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "Select", "InWin", "Not", "And", "Or", "HasWordOfDict", 
		"HasTime", "HasLocation", "HasOrganization", "HasURL", "HasDate", "HasQuestion", 
		"HasUserMentioned", "ByUser", "STRING", "INTEGER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Chat.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ChatParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ChatParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ChatParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class QueryContext : ParserRuleContext {
		public ITerminalNode Select() { return GetToken(ChatParser.Select, 0); }
		public BodyContext body() {
			return GetRuleContext<BodyContext>(0);
		}
		public QueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QueryContext query() {
		QueryContext _localctx = new QueryContext(Context, State);
		EnterRule(_localctx, 0, RULE_query);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 18; Match(Select);
			State = 19; body();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BodyContext : ParserRuleContext {
		public Restriction_groupContext[] restriction_group() {
			return GetRuleContexts<Restriction_groupContext>();
		}
		public Restriction_groupContext restriction_group(int i) {
			return GetRuleContext<Restriction_groupContext>(i);
		}
		public BodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_body; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BodyContext body() {
		BodyContext _localctx = new BodyContext(Context, State);
		EnterRule(_localctx, 2, RULE_body);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 21; restriction_group();
			State = 26;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 22; Match(T__0);
				State = 23; restriction_group();
				}
				}
				State = 28;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Restriction_groupContext : ParserRuleContext {
		public RestrictionsContext restrictions() {
			return GetRuleContext<RestrictionsContext>(0);
		}
		public ITerminalNode InWin() { return GetToken(ChatParser.InWin, 0); }
		public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public Restriction_groupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restriction_group; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestriction_group(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Restriction_groupContext restriction_group() {
		Restriction_groupContext _localctx = new Restriction_groupContext(Context, State);
		EnterRule(_localctx, 4, RULE_restriction_group);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 29; restrictions();
			State = 32;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==InWin) {
				{
				State = 30; Match(InWin);
				State = 31; number();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RestrictionsContext : ParserRuleContext {
		public RestrictionContext[] restriction() {
			return GetRuleContexts<RestrictionContext>();
		}
		public RestrictionContext restriction(int i) {
			return GetRuleContext<RestrictionContext>(i);
		}
		public RestrictionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restrictions; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestrictions(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RestrictionsContext restrictions() {
		RestrictionsContext _localctx = new RestrictionsContext(Context, State);
		EnterRule(_localctx, 6, RULE_restrictions);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34; restriction(0);
			State = 39;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 35; Match(T__1);
				State = 36; restriction(0);
				}
				}
				State = 41;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RestrictionContext : ParserRuleContext {
		public RestrictionContext[] restriction() {
			return GetRuleContexts<RestrictionContext>();
		}
		public RestrictionContext restriction(int i) {
			return GetRuleContext<RestrictionContext>(i);
		}
		public ITerminalNode Not() { return GetToken(ChatParser.Not, 0); }
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public ITerminalNode And() { return GetToken(ChatParser.And, 0); }
		public ITerminalNode Or() { return GetToken(ChatParser.Or, 0); }
		public RestrictionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_restriction; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRestriction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RestrictionContext restriction() {
		return restriction(0);
	}

	private RestrictionContext restriction(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		RestrictionContext _localctx = new RestrictionContext(Context, _parentState);
		RestrictionContext _prevctx = _localctx;
		int _startState = 8;
		EnterRecursionRule(_localctx, 8, RULE_restriction, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__2:
				{
				State = 43; Match(T__2);
				State = 44; restriction(0);
				State = 45; Match(T__3);
				}
				break;
			case Not:
				{
				State = 47; Match(Not);
				State = 48; restriction(2);
				}
				break;
			case HasWordOfDict:
			case HasTime:
			case HasLocation:
			case HasOrganization:
			case HasURL:
			case HasDate:
			case HasQuestion:
			case HasUserMentioned:
			case ByUser:
				{
				State = 49; condition();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 60;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 58;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
					case 1:
						{
						_localctx = new RestrictionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_restriction);
						State = 52;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 53; Match(And);
						State = 54; restriction(6);
						}
						break;
					case 2:
						{
						_localctx = new RestrictionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_restriction);
						State = 55;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 56; Match(Or);
						State = 57; restriction(5);
						}
						break;
					}
					} 
				}
				State = 62;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		public ITerminalNode HasWordOfDict() { return GetToken(ChatParser.HasWordOfDict, 0); }
		public HdictContext hdict() {
			return GetRuleContext<HdictContext>(0);
		}
		public ITerminalNode HasTime() { return GetToken(ChatParser.HasTime, 0); }
		public ITerminalNode HasLocation() { return GetToken(ChatParser.HasLocation, 0); }
		public ITerminalNode HasOrganization() { return GetToken(ChatParser.HasOrganization, 0); }
		public ITerminalNode HasURL() { return GetToken(ChatParser.HasURL, 0); }
		public ITerminalNode HasDate() { return GetToken(ChatParser.HasDate, 0); }
		public ITerminalNode HasQuestion() { return GetToken(ChatParser.HasQuestion, 0); }
		public ITerminalNode HasUserMentioned() { return GetToken(ChatParser.HasUserMentioned, 0); }
		public HuserContext huser() {
			return GetRuleContext<HuserContext>(0);
		}
		public ITerminalNode ByUser() { return GetToken(ChatParser.ByUser, 0); }
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 10, RULE_condition);
		try {
			State = 96;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case HasWordOfDict:
				EnterOuterAlt(_localctx, 1);
				{
				State = 63; Match(HasWordOfDict);
				State = 64; Match(T__2);
				State = 65; hdict();
				State = 66; Match(T__3);
				}
				break;
			case HasTime:
				EnterOuterAlt(_localctx, 2);
				{
				State = 68; Match(HasTime);
				State = 69; Match(T__2);
				State = 70; Match(T__3);
				}
				break;
			case HasLocation:
				EnterOuterAlt(_localctx, 3);
				{
				State = 71; Match(HasLocation);
				State = 72; Match(T__2);
				State = 73; Match(T__3);
				}
				break;
			case HasOrganization:
				EnterOuterAlt(_localctx, 4);
				{
				State = 74; Match(HasOrganization);
				State = 75; Match(T__2);
				State = 76; Match(T__3);
				}
				break;
			case HasURL:
				EnterOuterAlt(_localctx, 5);
				{
				State = 77; Match(HasURL);
				State = 78; Match(T__2);
				State = 79; Match(T__3);
				}
				break;
			case HasDate:
				EnterOuterAlt(_localctx, 6);
				{
				State = 80; Match(HasDate);
				State = 81; Match(T__2);
				State = 82; Match(T__3);
				}
				break;
			case HasQuestion:
				EnterOuterAlt(_localctx, 7);
				{
				State = 83; Match(HasQuestion);
				State = 84; Match(T__2);
				State = 85; Match(T__3);
				}
				break;
			case HasUserMentioned:
				EnterOuterAlt(_localctx, 8);
				{
				State = 86; Match(HasUserMentioned);
				State = 87; Match(T__2);
				State = 88; huser();
				State = 89; Match(T__3);
				}
				break;
			case ByUser:
				EnterOuterAlt(_localctx, 9);
				{
				State = 91; Match(ByUser);
				State = 92; Match(T__2);
				State = 93; huser();
				State = 94; Match(T__3);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public ITerminalNode INTEGER() { return GetToken(ChatParser.INTEGER, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 12, RULE_number);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 98; Match(INTEGER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HdictContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(ChatParser.STRING, 0); }
		public HdictContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hdict; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHdict(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HdictContext hdict() {
		HdictContext _localctx = new HdictContext(Context, State);
		EnterRule(_localctx, 14, RULE_hdict);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HuserContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(ChatParser.STRING, 0); }
		public HuserContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_huser; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IChatVisitor<TResult> typedVisitor = visitor as IChatVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHuser(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HuserContext huser() {
		HuserContext _localctx = new HuserContext(Context, State);
		EnterRule(_localctx, 16, RULE_huser);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 4: return restriction_sempred((RestrictionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool restriction_sempred(RestrictionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		case 1: return Precpred(Context, 4);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x17', 'k', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 
		'\x1B', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x1E', '\v', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '#', '\n', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '(', '\n', '\x5', '\f', 
		'\x5', '\xE', '\x5', '+', '\v', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', '\x35', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', '=', 
		'\n', '\x6', '\f', '\x6', '\xE', '\x6', '@', '\v', '\x6', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 
		'\x63', '\n', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x2', '\x3', '\n', '\v', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x2', '\x2', '\x2', 
		'p', '\x2', '\x14', '\x3', '\x2', '\x2', '\x2', '\x4', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x6', '\x1F', '\x3', '\x2', '\x2', '\x2', '\b', 
		'$', '\x3', '\x2', '\x2', '\x2', '\n', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\f', '\x62', '\x3', '\x2', '\x2', '\x2', '\xE', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '\x10', '\x66', '\x3', '\x2', '\x2', '\x2', '\x12', 'h', 
		'\x3', '\x2', '\x2', '\x2', '\x14', '\x15', '\a', '\a', '\x2', '\x2', 
		'\x15', '\x16', '\x5', '\x4', '\x3', '\x2', '\x16', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x17', '\x1C', '\x5', '\x6', '\x4', '\x2', '\x18', '\x19', 
		'\a', '\x3', '\x2', '\x2', '\x19', '\x1B', '\x5', '\x6', '\x4', '\x2', 
		'\x1A', '\x18', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\x1C', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1F', '\"', '\x5', '\b', 
		'\x5', '\x2', ' ', '!', '\a', '\b', '\x2', '\x2', '!', '#', '\x5', '\xE', 
		'\b', '\x2', '\"', ' ', '\x3', '\x2', '\x2', '\x2', '\"', '#', '\x3', 
		'\x2', '\x2', '\x2', '#', '\a', '\x3', '\x2', '\x2', '\x2', '$', ')', 
		'\x5', '\n', '\x6', '\x2', '%', '&', '\a', '\x4', '\x2', '\x2', '&', '(', 
		'\x5', '\n', '\x6', '\x2', '\'', '%', '\x3', '\x2', '\x2', '\x2', '(', 
		'+', '\x3', '\x2', '\x2', '\x2', ')', '\'', '\x3', '\x2', '\x2', '\x2', 
		')', '*', '\x3', '\x2', '\x2', '\x2', '*', '\t', '\x3', '\x2', '\x2', 
		'\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', ',', '-', '\b', '\x6', '\x1', 
		'\x2', '-', '.', '\a', '\x5', '\x2', '\x2', '.', '/', '\x5', '\n', '\x6', 
		'\x2', '/', '\x30', '\a', '\x6', '\x2', '\x2', '\x30', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x32', '\a', '\t', '\x2', '\x2', '\x32', 
		'\x35', '\x5', '\n', '\x6', '\x4', '\x33', '\x35', '\x5', '\f', '\a', 
		'\x2', '\x34', ',', '\x3', '\x2', '\x2', '\x2', '\x34', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x34', '\x33', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'>', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\f', '\a', '\x2', '\x2', 
		'\x37', '\x38', '\a', '\n', '\x2', '\x2', '\x38', '=', '\x5', '\n', '\x6', 
		'\b', '\x39', ':', '\f', '\x6', '\x2', '\x2', ':', ';', '\a', '\v', '\x2', 
		'\x2', ';', '=', '\x5', '\n', '\x6', '\a', '<', '\x36', '\x3', '\x2', 
		'\x2', '\x2', '<', '\x39', '\x3', '\x2', '\x2', '\x2', '=', '@', '\x3', 
		'\x2', '\x2', '\x2', '>', '<', '\x3', '\x2', '\x2', '\x2', '>', '?', '\x3', 
		'\x2', '\x2', '\x2', '?', '\v', '\x3', '\x2', '\x2', '\x2', '@', '>', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\f', '\x2', '\x2', 
		'\x42', '\x43', '\a', '\x5', '\x2', '\x2', '\x43', '\x44', '\x5', '\x10', 
		'\t', '\x2', '\x44', '\x45', '\a', '\x6', '\x2', '\x2', '\x45', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', '\r', '\x2', '\x2', 'G', 
		'H', '\a', '\x5', '\x2', '\x2', 'H', '\x63', '\a', '\x6', '\x2', '\x2', 
		'I', 'J', '\a', '\xE', '\x2', '\x2', 'J', 'K', '\a', '\x5', '\x2', '\x2', 
		'K', '\x63', '\a', '\x6', '\x2', '\x2', 'L', 'M', '\a', '\xF', '\x2', 
		'\x2', 'M', 'N', '\a', '\x5', '\x2', '\x2', 'N', '\x63', '\a', '\x6', 
		'\x2', '\x2', 'O', 'P', '\a', '\x10', '\x2', '\x2', 'P', 'Q', '\a', '\x5', 
		'\x2', '\x2', 'Q', '\x63', '\a', '\x6', '\x2', '\x2', 'R', 'S', '\a', 
		'\x11', '\x2', '\x2', 'S', 'T', '\a', '\x5', '\x2', '\x2', 'T', '\x63', 
		'\a', '\x6', '\x2', '\x2', 'U', 'V', '\a', '\x12', '\x2', '\x2', 'V', 
		'W', '\a', '\x5', '\x2', '\x2', 'W', '\x63', '\a', '\x6', '\x2', '\x2', 
		'X', 'Y', '\a', '\x13', '\x2', '\x2', 'Y', 'Z', '\a', '\x5', '\x2', '\x2', 
		'Z', '[', '\x5', '\x12', '\n', '\x2', '[', '\\', '\a', '\x6', '\x2', '\x2', 
		'\\', '\x63', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '\x14', '\x2', 
		'\x2', '^', '_', '\a', '\x5', '\x2', '\x2', '_', '`', '\x5', '\x12', '\n', 
		'\x2', '`', '\x61', '\a', '\x6', '\x2', '\x2', '\x61', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x41', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '\x62', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\x62', 'L', '\x3', '\x2', '\x2', '\x2', '\x62', 'O', '\x3', '\x2', 
		'\x2', '\x2', '\x62', 'R', '\x3', '\x2', '\x2', '\x2', '\x62', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\x62', 'X', '\x3', '\x2', '\x2', '\x2', '\x62', 
		']', '\x3', '\x2', '\x2', '\x2', '\x63', '\r', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x65', '\a', '\x16', '\x2', '\x2', '\x65', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x66', 'g', '\a', '\x15', '\x2', '\x2', 'g', '\x11', '\x3', 
		'\x2', '\x2', '\x2', 'h', 'i', '\a', '\x15', '\x2', '\x2', 'i', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x1C', '\"', ')', '\x34', '<', '>', 
		'\x62',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
